# Generated by Django 6.0.5 on 2026-06-03 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('bank_name', models.CharField(max_length=100, verbose_name='nome do banco')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Conta Poupança'), ('WALLET', 'Carteira')], default='CHECKING', max_length=20, verbose_name='tipo de conta')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_ac_user_id_0bca0f_idx'), models.Index(fields=['user', 'account_type'], name='accounts_ac_user_id_79e366_idx')],
            },
        ),
    ]
